### ISSUE TITLE
Crear HBM e Obxecto modelo de Asistencia

### ISSUE THREAD

**Issue by pbelay** [aulanosaad/aulanosa#4]
Crear HBM e Obxecto modelo de Asistencia

**Comment by pablord94** [comment]
(HBM Asistencia) Creamos la relación many-to-one .
(Clase Asistencia) Creamos una clase para Asistencia con sus atributos, getters/setters y toString.
(SQL DatosPersonales) Creamos un sql para insertar datos de Asistencia.
(MainAsistencia(Paquete Nuevo)) Creamos una main en un paquete diferente donde probamos los métodos de GenericDAO(create(Asistencia), upadte(Asistencia), delete(Asistencia),getAll(Asistencia) ).
