### ISSUE TITLE
Crear HBM e Obxecto modelo de datopersonal

### ISSUE THREAD

**Issue by pbelay** [aulanosaad/aulanosa#8]
==TAREFAS ===

**Comment by andresbarca** [comment]
- (HBM DatosPersonales) Creamos la relación one-to-one .
- (Clase DatosPersonales) Creamos una clase para DatosPersonales con sus atributos, getters/setters y toString.
- (SQL DatosPersonales) Creamos un sql para insertar datos de DatosPersonales y borramos la clave foránea en la B.D. 
- (MainTestDAODatosPersonales(Paquete Nuevo)) Creamos una main en un paquete diferente donde probamos los métodos de GenericDAO(create(datosPersonales) y findById(Alumno)).
- (Short-Int) Cambiamos el valor del atributo id de short a int.
